#!/bin/bash

echo Running pre-push hook...
if [ "$NO_GIT_HOOKS" = true ]; then
    echo NO_GIT_HOOKS="$NO_GIT_HOOKS" so aborting hook.
    exit 0
fi
export COMMIT_MSG='pre-push hook: build site.'
# Ignore "chore" commits
export prev_msg="$(git show --no-patch --format=%B)"
if [[ "$prev_msg" == chore* || "$prev_msg" == Chore* ]]; then
    echo "pre-push: Not building site for 'chore' commit."
    exit 0
fi
# Try to build the website.
bash _scripts/build-site.sh
[ $? -ne 0 ] && echo "Failed to build site. Aborting pre-push hook." && exit 1
# Add the relevant files
git add index.html script.js stylesheet.css posts
# Commit the website
git commit -m "$COMMIT_MSG"
# Ok for commit to fail, e.g. have already built site
# or haven't changed site,
# so need to make sure script exits with 0,
# or push will fail.
[ $? -ne 0 ] && exit 0