#!/bin/bash

echo Running pre-commit hook...
if [ "$NO_GIT_HOOKS" = true ]; then
    echo NO_GIT_HOOKS="$NO_GIT_HOOKS" so aborting hook.
    exit 0
fi

black _notebooks --check
[ $? -ne 0 ] && echo "Aborting commit: run black before committing." && exit 1

echo "Pre-commit completed successfully."
